### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by Quy** [GetLuna/Luna#1496]
`viewforum.php`
Notice: Undefined variable: sql_addition in C:\xampp\htdocs\projects\Luna\include\draw_functions.php on line 239

Notice: Undefined variable: forum_name in C:\xampp\htdocs\projects\Luna\themes\Fifteen\objects\thread.php on line 10

`Moderate forum`
Notice: Undefined index: has_commented in C:\xampp\htdocs\projects\Luna\backstage\moderate.php on line 932

Undefined variable: subject_new_comments in C:\xampp\htdocs\projects\Luna\backstage\moderate.php on line 955

`search.php`
Notice: Undefined index: pid in C:\xampp\htdocs\projects\Luna\include\draw_functions.php on line 1003

`sqlite3`
On all front-end pages:
Notice: Undefined offset: 0 in C:\xampp\htdocs\projects\Luna\include\dblayer\sqlite3.php on line 128
due to this:
```$result_header = $db->query('SELECT 1 FROM '.$db->prefix.'reports WHERE zapped IS NULL') or error('Unable to fetch reports info', __FILE__, __LINE__, $db->error());```

index, userlist, viewforum, viewtopic:
Notice: Undefined offset: 1 in C:\xampp\htdocs\projects\Luna\include\dblayer\sqlite3.php on line 128

PHP Notice:  Undefined variable: action in C:\xampp\htdocs\projects\Luna\ajax.php on line 25

**Comment by Studio384** [comment]
`viewforum.php`
- [ ] Notice: Undefined variable: sql_addition in
 - C:\xampp\htdocs\projects\Luna\include\draw_functions.php on line 239

- [ ] Notice: Undefined variable: forum_name in 
 - C:\xampp\htdocs\projects\Luna\themes\Fifteen\objects\thread.php on line 10

`Moderate forum`
- [ ] Notice: Undefined index: has_commented in 
 - C:\xampp\htdocs\projects\Luna\backstage\moderate.php on line 932

- [ ] Undefined variable: subject_new_comments in 
 - C:\xampp\htdocs\projects\Luna\backstage\moderate.php on line 955

`search.php`
- [ ] Notice: Undefined index: pid in
 - C:\xampp\htdocs\projects\Luna\include\draw_functions.php on line 1003

`sqlite3`
On all front-end pages:
- [ ] Notice: Undefined offset: 0 in
 - C:\xampp\htdocs\projects\Luna\include\dblayer\sqlite3.php on line 128
due to this:
```$result_header = $db->query('SELECT 1 FROM '.$db->prefix.'reports WHERE zapped IS NULL') or error('Unable to fetch reports info', __FILE__, __LINE__, $db->error());```

index, userlist, viewforum, viewtopic:
- [ ]  Notice: Undefined offset: 1 in
 - C:\xampp\htdocs\projects\Luna\include\dblayer\sqlite3.php on line 128

- [ ] PHP Notice:  Undefined variable: action in
 - C:\xampp\htdocs\projects\Luna\ajax.php on line 25

**Comment by Studio384** [comment]
I think that should do the trick
